// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: remotemap.proto

#include "remotemap.pb.h"
#include "remotemap.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace remotemap {

static const char* PBCalculations_method_names[] = {
  "/remotemap.PBCalculations/calcCost",
};

std::unique_ptr< PBCalculations::Stub> PBCalculations::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PBCalculations::Stub> stub(new PBCalculations::Stub(channel));
  return stub;
}

PBCalculations::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_calcCost_(PBCalculations_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status PBCalculations::Stub::calcCost(::grpc::ClientContext* context, const ::remotemap::PBShipmentInfo& request, ::remotemap::Float* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_calcCost_, context, request, response);
}

void PBCalculations::Stub::experimental_async::calcCost(::grpc::ClientContext* context, const ::remotemap::PBShipmentInfo* request, ::remotemap::Float* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_calcCost_, context, request, response, std::move(f));
}

void PBCalculations::Stub::experimental_async::calcCost(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::remotemap::Float* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_calcCost_, context, request, response, std::move(f));
}

void PBCalculations::Stub::experimental_async::calcCost(::grpc::ClientContext* context, const ::remotemap::PBShipmentInfo* request, ::remotemap::Float* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_calcCost_, context, request, response, reactor);
}

void PBCalculations::Stub::experimental_async::calcCost(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::remotemap::Float* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_calcCost_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::remotemap::Float>* PBCalculations::Stub::AsynccalcCostRaw(::grpc::ClientContext* context, const ::remotemap::PBShipmentInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::remotemap::Float>::Create(channel_.get(), cq, rpcmethod_calcCost_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::remotemap::Float>* PBCalculations::Stub::PrepareAsynccalcCostRaw(::grpc::ClientContext* context, const ::remotemap::PBShipmentInfo& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::remotemap::Float>::Create(channel_.get(), cq, rpcmethod_calcCost_, context, request, false);
}

PBCalculations::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PBCalculations_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< PBCalculations::Service, ::remotemap::PBShipmentInfo, ::remotemap::Float>(
          [](PBCalculations::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::remotemap::PBShipmentInfo* req,
             ::remotemap::Float* resp) {
               return service->calcCost(ctx, req, resp);
             }, this)));
}

PBCalculations::Service::~Service() {
}

::grpc::Status PBCalculations::Service::calcCost(::grpc::ServerContext* context, const ::remotemap::PBShipmentInfo* request, ::remotemap::Float* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace remotemap

